networks:
  webnet:
    name: webnet
    driver: bridge

services:
  website:
    container_name: website
    image: website
    build: ./requirements/website
    ports:
      - 8000:8000
    networks:
      - webnet
    restart: unless-stopped
