networks:
  webnet:
    name: webnet
    driver: bridge

services:
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   build: ./requirements/postgres
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - webnet
  #   restart: unless-stopped
  website:
    container_name: website
    image: website
    build: ./requirements/website
    env_file:
      - .env
    # depends_on:
    #   - postgres
    ports:
      - $HOSTPORT:$HOSTPORT
    networks:
      - webnet
    restart: unless-stopped
