networks:
  webnet:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      device: "./data/postgres"
      o: bind

services:
  website:
    container_name: website
    build: ./requirements/website
    ports:
      - 8000:8000
    networks:
      - webnet
    env_file:
      - .env
    restart: unless-stopped
